PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX arena: <https://solid.ti.rw.fau.de/public/ns/arena#>
PREFIX sim: <http://ti.rw.fau.de/sim#>

# For blue stations if no product create a product that is not blue
#DELETE {
#    # Empty
#} INSERT {
#    GRAPH ?station {
#        ?port arena:products ?product .
#    }
#    GRAPH ?product {
#        ?product a arena:Product ;
#            arena:color ?color .
#    }
#} WHERE {
#    # Random possibility to assign a product
#    BIND (sim:rand(?station) AS ?rand)
#    #TODO
#
#    # Assign the product to the generated URI and bind as product which is then assigned to the station's graph above
#    BIND(URI(CONCAT("/products/", STRUUID())) AS ?product)
#
#    # Draw one color for the product that is not the station's color
#    {
#        SELECT (SAMPLE(?c) AS ?color)
#        WHERE {
#	  #TODO
#        }
#    }
#
#    ?station a arena:Workstation ;
#      # TODO
#
#    # Consider only stations whose port has no product 
#    FILTER NOT EXISTS {    
#      #TODO
#    }
#};
